DROP TABLE IF EXISTS users;
CREATE TABLE users (
	user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	fullname VARCHAR(40),
	email VARCHAR(30)
) ENGINE=INNODB;

DROP TABLE IF EXISTS projects;
CREATE TABLE projects (
	project_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(500),
	create_date DATETIME
) ENGINE=INNODB;

DROP TABLE IF EXISTS todos;
CREATE TABLE todos (
	todo_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	project_id INT NOT NULL,
	user_id INT NOT NULL,
	title VARCHAR(200),
	description VARCHAR(500),
	assign_date DATETIME,
	due_data DATETIME,
	isdone BOOLEAN DEFAULT false
) ENGINE=INNODB;

ALTER TABLE todos ADD CONSTRAINT FK_project_id FOREIGN KEY (project_id) REFERENCES projects(project_id)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE todos ADD CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(user_id)
ON UPDATE CASCADE ON DELETE CASCADE;
